taste_shop/shop/urls.py
from django.urls import path

from .views import index, author, contact, product, item

app_name = 'shop'

urlpatterns = [
    path('', index, name='index'),
    path('autor/', author, name='autor'),
    path('contact/', contact, name='contact'),
    path('product/', product, name='product'),
    path('item/<int:lot_id>/', item, name='item')
]

taste_shop/taste_shop/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:  # add this
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

taste_shop/users/urls.py
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.contrib.auth.views import PasswordChangeDoneView
from django.urls import path

from . import views

app_name = 'users'


urlpatterns = [
    path(
        'login/',
        LoginView.as_view(
            template_name='users/login.html'
        ),
        name='login'),
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'logout/',
        LogoutView.as_view(
            template_name='users/logged_out.html'
        ),
        name='logout'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
]

taste_shop/shop/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class CardShopItem(models.Model):
    SIZE = (
        ('XS', 'XS'),
        ('S', 'S'),
        ('M', 'M'),
        ('L', 'L'),
        ('XL', 'XL'),
        ('XXL', 'XXL'),
    )
    TAGS = (
        ('Shoes', 'Shoes'),
        ('Socks', 'Socks'),
        ('Underpants', 'Underpants'),
        ('Trousers', 'Trousers'),
        ('Shorts', 'Shorts'),
        ('T-shirt', 'T-shirt'),
        ('Hoodie', 'Hoodie'),
        ('Jacket', 'Jacket'),
        ('Sweater', 'Sweater'),
    )
    name = models.CharField(
        max_length=100
    )
    size = models.CharField(
        choices=SIZE,
        max_length=100
    )
    description = models.TextField(
        blank=False,
        null=False,
    )
    image = models.ImageField(
        upload_to='shouse/',
        blank=False,
        null=False,
    )
    tag = models.CharField(
        choices=TAGS,
        max_length=100,
    )
    slug = models.SlugField(
        max_length=255,
        unique=True,
        verbose_name='URL',
    )
    prise = models.IntegerField(
        blank=False,
        null=False,
        default=0
    )
    amount = models.IntegerField(
        blank=False,
        null=False,
        default=0
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = 'Лот'
        verbose_name_plural = 'Одежда'


class Comment(models.Model):
    post = models.ForeignKey(
        CardShopItem,
        null=True,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='К лоту',
        blank=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария',
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return 'Комментарий'

taste_shop/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

taste_shop/shop/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.conf import settings

from .models import CardShopItem, Comment


def page_breakdown(page_number, objects):
    paginator = Paginator(objects, settings.COUNT_POST)
    return paginator.get_page(page_number)


def index(request):
    lot = CardShopItem.objects.all()
    coments = Comment.objects.select_related(
        'post'
    ).count()
    context = {
        'page_obj': lot,
        'comment_count': coments,
        'title': 'Stonks'
    }
    return render(request, 'shop/index.html', context)


def contact(request):
    context = {
        'title': 'Контакты'
    }
    return render(request, 'shop/contact.html', context)


def product(request):
    lot = CardShopItem.objects.all()
    coments = Comment.objects.select_related(
        'post'
    ).count()
    page_number = request.GET.get('page')
    context = {
        'page_obj': page_breakdown(page_number, lot),
        'comment_count': coments,
        'title': 'Контакты'
    }
    return render(request, 'shop/products.html', context)


def item(request, lot_id):
    lot = get_object_or_404(Comment, id=lot_id)
    context = {
        'lot': lot,
    }
    return render(request, 'shop/item.html', context)


def author(request):
    context = {
        'title': 'Автор сего чуда'
    }
    return render(request, 'shop/about.html', context)

taste_shop/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.contrib.auth import login
from django.shortcuts import redirect

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('shop:index')
    template_name = 'users/login.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('shop:index')

taste_shop/templates/inc/footer.html
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="inner-content">
              <p>
                Стоит признаться что я позаимствовал шаблон у ребят с  интернета
                И даже не оставлю на них ссылку
              </p>
            </div>
          </div>
        </div>
      </div>
    </footer>

taste_shop/templates/inc/head.html
{% load static %}

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">
    <title>{{ title }}</title>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-sixteenb.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.css' %}">

</head>

taste_shop/templates/inc/header.html
<header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="{% url 'shop:index' %}"><h2>Sixteen <em>Clothing</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'shop:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'shop:product' %}">Our Products</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'shop:autor' %}">About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'shop:contact' %}">Contact Us</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:password_change' %}">Password Change</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Register/Login</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </header>

taste_shop/templates/inc/paginator.html
{% if page_obj.has_other_pages %}
<div class="col-md-12">
  <ul class="pages">
    {% if page_obj.has_previous %}
      <li><a href="?page=1">F</a></li>
      <li><a href="?page={{ page_obj.previous_page_number }}">L</a></li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active">{{ i }}</li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">N</a></li>
      <li><a href="?page={{ page_obj.paginator.num_pages }}">L</a></li>
    {% endif %}
  </ul>
</div>
{% endif %}

taste_shop/templates/inc/preloader.html
<div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
</div>

taste_shop/templates/inc/scr.html
{% load static %}

<script src="{% static 'jquery/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/owl.js' %}"></script>
<script src="{% static 'js/slick.js' %}"></script>
<script src="{% static 'js/isotope.js' %}"></script>
<script src="{% static 'js/accordions.js' %}"></script>
<script language = "text/Javascript">
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }
</script>

taste_shop/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  {% include 'inc/head.html' %}

  <body>
    {% include 'inc/preloader.html' %}
    {% include 'inc/header.html' %}
    <div class="banner header-text">
      <div class="owl-banner owl-carousel">
        <div class="banner-item-01">
          <div class="text-content">
            <h4>Best Offer</h4>
            <h2>New Arrivals On Sale</h2>
          </div>
        </div>
        <div class="banner-item-02">
          <div class="text-content">
            <h4>Flash Deals</h4>
            <h2>Get your best products</h2>
          </div>
        </div>
        <div class="banner-item-03">
          <div class="text-content">
            <h4>Last Minute</h4>
            <h2>Grab last minute deals</h2>
          </div>
        </div>
      </div>
    </div>
    <!-- Banner Ends Here -->

    <div class="latest-products">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>Latest Products</h2>
              <a href="{% url 'shop:product' %}">view all products <i class="fa fa-angle-right"></i></a>
            </div>
          </div>
          {% for lot in page_obj %}
          <div class="col-md-4">
            <div class="product-item">
              <a href="{{ lot.slug }}"><img src="/media/{{ lot.image }}" alt=""></a>
              <div class="down-content">
                <a href="{{ lot.slug }}"><h4>{{ lot.name }}</h4></a>
                <h6>${{ lot.prise }}</h6>
                <p>{{ lot.description }}</p>
                <span>Reviews ({{ comment_count }})</span>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
    {% include 'inc/footer.html' %}
    {% include 'inc/scr.html' %}
  </body>

</html>

taste_shop/templates/products.html
<!DOCTYPE html>

<html lang="en">

{% include 'inc/head.html' %}

  <body>
    {% include 'inc/preloader.html' %}
    {% include 'inc/header.html' %}
    <div class="page-heading products-heading header-text">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="text-content">
              <h4>new arrivals</h4>
              <h2>sixteen products</h2>
            </div>
          </div>
        </div>
      </div>
    </div>

    
    <div class="products">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="filters">
              <ul>
                  <li class="active" data-filter="*">All Products</li>
                  <li data-filter=".des">Featured</li>
                  <li data-filter=".dev">Flash Deals</li>
                  <li data-filter=".gra">Last Minute</li>
              </ul>
            </div>
          </div>
          <div class="col-md-12">
            <div class="filters-content">
                <div class="row grid">
                  {% for lot in page_obj %}
                    <div class="col-lg-4 col-md-4 all dev">
                      <div class="product-item">
                        <a href="{{ lot.slug }}"><img src="/media/{{ lot.image }}" alt=""></a>
                        <div class="down-content">
                          <a href="{{ lot.slug }}"><h4>{{ lot.name }}</h4></a>
                          <h6>{{ lot.prise }}</h6>
                          <p>{{ lot.description }}</p>
                          <span>Reviews ({{ comment_count }})</span>
                        </div>
                      </div>
                    </div>
                  {% endfor %}
                </div>
            </div>
          </div>
          {% include 'inc/paginator.html' %}
        </div>
      </div>
    </div>
    {% include 'inc/footer.html' %}
    {% include 'inc/scr.html' %}


  </body>

</html>

taste_shop/templates/shop/about.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  {% include 'inc/head.html' %}

  <body>
    {% include 'inc/preloader.html' %}
    {% include 'inc/header.html' %}
    <div class="page-heading about-heading header-text">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="text-content">
              <h4>about us</h4>
              <h2>our company</h2>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="best-features about-features">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>Our Background</h2>
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-image">
              <img src="{% static 'images/about_f.jpg' %}" alt="">
            </div>
          </div>
          <div class="col-md-6">
            <div class="left-content">
              <h4>Who we are &amp; What we do?</h4>
              <p class="text_about_me">
                Привет, меня Сергей, мне 17 лет. Проживаю в СПб.
                Занимайюсь разработкой на Python уже год и это один из моих проектов.
                Как видно из картинки - я ганкстер. Люблю играть на гитаре, а так же в баскетбол
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% include 'inc/footer.html' %}
    {% include 'inc/scr.html' %}
  </body>

</html>

taste_shop/templates/shop/contact.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

  {% include 'inc/head.html' %}

  <body>
    {% include 'inc/preloader.html' %}
    {% include 'inc/header.html' %}
    <div class="page-heading contact-heading header-text">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="text-content">
              <h4>contact us</h4>
              <h2>let’s get in touch</h2>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="find-us">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>Our Location on Maps</h2>
            </div>
          </div>
          <div class="col-md-8">
            <div id="map">
              <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d7988.6891825407565!2d30.28996857612945!3d59.96246541662604!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sru!2sru!4v1695745252257!5m2!1sru!2sru" width="600" height="280" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
          </div>
          <div class="col-md-4">
            <div class="left-content">
              <h4>About our office</h4>
              <p>
                One of the most popular tourist attractions in Saint Petersburg is the Hermitage Museum<br>
                <br>which houses over three million works of art,
                including paintings by famous artists such as Rembrandt and Leonardo da Vinci.
                The museum is housed in the Winter Palace, a beautiful building with ornate architecture and stunning interiors.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>

    
    <div class="send-message">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>Send us a Message</h2>
            </div>
          </div>
          <div class="col-md-8">
            <div class="contact-form">
              <form id="contact" action="" method="post">
                <div class="row">
                  <div class="col-lg-12 col-md-12 col-sm-12">
                    <fieldset>
                      <input name="name" type="text" class="form-control" id="name" placeholder="Full Name" required="">
                    </fieldset>
                  </div>
                  <div class="col-lg-12 col-md-12 col-sm-12">
                    <fieldset>
                      <input name="email" type="text" class="form-control" id="email" placeholder="E-Mail Address" required="">
                    </fieldset>
                  </div>
                  <div class="col-lg-12 col-md-12 col-sm-12">
                    <fieldset>
                      <input name="subject" type="text" class="form-control" id="subject" placeholder="Subject" required="">
                    </fieldset>
                  </div>
                  <div class="col-lg-12">
                    <fieldset>
                      <textarea name="message" rows="6" class="form-control" id="message" placeholder="Your Message" required=""></textarea>
                    </fieldset>
                  </div>
                  <div class="col-lg-12">
                    <fieldset>
                      <button type="submit" id="form-submit" class="filled-button">Send Message</button>
                    </fieldset>
                  </div>
                </div>
              </form>
            </div>
          </div>
          <div class="col-md-4">
            <ul class="accordion">
              <li>
                  <a>Вы правда хотите со мной связаться?</a>
                  <div class="content">
                      <p>Круто</p>
                  </div>
              </li>
              <li>
                  <a>Попробуйте мне отправить письмо на email</a>
                  <div class="content">
                      <p>Надеюсь форма рабочая</p>
                  </div>
              </li>
              <li>
                  <a>Я правда живу в Питере</a>
                  <div class="content">
                      <p>True</p>
                  </div>
              </li>
              <li>
                  <a>Было дело</a>
                  <div class="content">
                      <p>True</p>
                  </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    {% include 'inc/footer.html' %}
    {% include 'inc/scr.html' %}
  </body>

</html>

taste_shop/templates/shop/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  {% include 'inc/head.html' %}

  <body>
    {% include 'inc/preloader.html' %}
    {% include 'inc/header.html' %}
    <div class="banner header-text">
      <div class="owl-banner owl-carousel">
        <div class="banner-item-01">
          <div class="text-content">
            <h4>Best Offer</h4>
            <h2>New Arrivals On Sale</h2>
          </div>
        </div>
        <div class="banner-item-02">
          <div class="text-content">
            <h4>Flash Deals</h4>
            <h2>Get your best products</h2>
          </div>
        </div>
        <div class="banner-item-03">
          <div class="text-content">
            <h4>Last Minute</h4>
            <h2>Grab last minute deals</h2>
          </div>
        </div>
      </div>
    </div>
    <!-- Banner Ends Here -->

    <div class="latest-products">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>Latest Products</h2>
              <a href="{% url 'shop:product' %}">view all products <i class="fa fa-angle-right"></i></a>
            </div>
          </div>
          {% for lot in page_obj %}
          <div class="col-md-4">
            <div class="product-item">
              <a href="{% url 'shop:item' lot.id %}"><img src="/media/{{ lot.image }}" alt=""></a>
              <div class="down-content">
                <a href="{% url 'shop:item' lot.id %}"><h4>{{ lot.name }}</h4></a>
                <h6>${{ lot.prise }}</h6>
                <p>{{ lot.description| truncatewords:4 }}</p>
                <span>Reviews ({{ comment_count }})</span>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
    {% include 'inc/footer.html' %}
    {% include 'inc/scr.html' %}
  </body>

</html>

taste_shop/templates/shop/item.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  {% include 'inc/head.html' %}

  <body>
    {% include 'inc/header.html' %}
    {% include 'inc/footer.html' %}
    {% include 'inc/scr.html' %}
  </body>

</html>

taste_shop/templates/shop/products.html
<!DOCTYPE html>

<html lang="en">

{% include 'inc/head.html' %}

  <body>
    {% include 'inc/preloader.html' %}
    {% include 'inc/header.html' %}
    <div class="page-heading products-heading header-text">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="text-content">
              <h4>new arrivals</h4>
              <h2>sixteen products</h2>
            </div>
          </div>
        </div>
      </div>
    </div>

    
    <div class="products">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="filters">
              <ul>
                  <li class="active" data-filter="*">All Products</li>
                  <li data-filter=".des">Featured</li>
                  <li data-filter=".dev">Flash Deals</li>
                  <li data-filter=".gra">Last Minute</li>
              </ul>
            </div>
          </div>
          <div class="col-md-12">
            <div class="filters-content">
                <div class="row grid">
                  {% for lot in page_obj %}
                    <div class="col-lg-4 col-md-4 all dev">
                      <div class="product-item">
                        <a href="{{ lot.slug }}"><img src="/media/{{ lot.image }}" alt=""></a>
                        <div class="down-content">
                          <a href="{{ lot.slug }}"><h4>{{ lot.name }}</h4></a>
                          <h6>{{ lot.prise }}</h6>
                          <p>{{ lot.description| truncatewords:4 }}</p>
                          <span>Reviews ({{ comment_count }})</span>
                        </div>
                      </div>
                    </div>
                  {% endfor %}
                </div>
            </div>
          </div>
          {% include 'inc/paginator.html' %}
        </div>
      </div>
    </div>
    {% include 'inc/footer.html' %}
    {% include 'inc/scr.html' %}


  </body>

</html>

taste_shop/templates/shop_start/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="icon" href="{% static 'img/fav/126122.png'%}" type="image">
      <meta name="msapplication-TileColor" content="#000">
      <meta name="theme-color" content="#ffffff">
      <link rel="stylesheet" href="{% static 'css/body.css'%}">
      <link rel="stylesheet" href="{% static 'css/header.css'%}">
      <link rel="stylesheet" href="{% static 'css/header.css'%}">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
      <title>{% block title %}{%endblock%}</title>
    </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      <div class="container py-5">
        {% block content %}
        {% endblock %}
      </div>
    </main>
    <footer>
      {% include 'includes/footer.html' %}
    </footer>
  <script src="static/js/header.js"></script>
  </body>
</html>

taste_shop/templates/users/logged_out.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  {% include 'inc/head.html' %}

  <body>
    {% include 'inc/preloader.html' %}
    {% include 'inc/header.html' %}
   <div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
    {% include 'inc/footer.html' %}
    {% include 'inc/scr.html' %}
  </body>

</html>

taste_shop/templates/users/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  {% include 'inc/head.html' %}

  <body>
    {% include 'inc/preloader.html' %}
    {% include 'inc/header.html' %}
     <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card" style="margin-top: 201px;">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %}
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'users:signup' %}">
              Register
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
    {% include 'inc/footer.html' %}
    {% include 'inc/scr.html' %}
  </body>

</html>

taste_shop/templates/users/password_change_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

taste_shop/templates/users/password_change_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

taste_shop/templates/users/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>